import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * サイドバーを作成することで、以下のことができます：
 - ドキュメントの順序付けられたグループを作成する
 - そのグループの各ドキュメントに対してサイドバーを表示する
 - 次へ/前へのナビゲーションを提供する

 サイドバーはファイルシステムから生成するか、ここで明示的に定義することができます。

 好きなだけサイドバーを作成できます。

 自動でサイドバーを作成できます。
  githubGuidelinesSidebar: [{type: 'autogenerated', dirName: 'github-guidelines'}],

 手動でサイドバーを作成することもできます。
  githubGuidelinesSidebar: [
    'github-guidelines/index',
    {
      type: 'category',
      label: 'GitHub Guidelines',
      link: {
        type: 'doc',
        id: 'github-guidelines/index',
      },
      items: [
        'github-guidelines/contents',
      ],
    },
  ],
 */
const sidebars: SidebarsConfig = {
  siteGuidanceSidebar: [
    'site-guidance/site-guidance-index',
    'site-guidance/site-guidance-planned-content-and-update-history',
    'site-guidance/site-guidance-credits',
  ],
  githubGuidelinesSidebar: [
    'github-guidelines/github-guidelines-index',
    'github-guidelines/github-guidelines-writing-guide',
    'github-guidelines/github-guidelines-repository-naming-policy',
    'github-guidelines/github-guidelines-branch-strategy',
  ],
  technicalPoliciesSidebar: [
    'technical-policies/technical-policies-index',
    'technical-policies/technical-policies-writing-guide',
    {
      type: 'category',
      label: 'C# および .NET 関連の技術',
      items: [
        'technical-policies/csharp/technical-policies-csharp-names-of-namespaces',
      ],
    }
  ],
  technicalNotebookSidebar: [
    'technical-notebook/technical-notebook-index',
    'technical-notebook/technical-notebook-writing-guide',
    {
      type: 'category',
      label: 'C# および .NET 関連の技術',
      items: [
        {
          type: 'category',
          label: 'GitHub Actions',
          items: [
            'technical-notebook/dotnet/github-actions/technical-notebook-dotnet-github-actions-automatic-test-execution',
            'technical-notebook/dotnet/github-actions/technical-notebook-dotnet-github-actions-vulnerability-scan',
          ],
        },
        {
          type: 'category',
          label: 'HTTP プロトコル',
          items: [
            'technical-notebook/dotnet/http-protocol/technical-notebook-dotnet-http-protocol-basic-explanation',
            'technical-notebook/dotnet/http-protocol/technical-notebook-dotnet-http-protocol-get-method',
            'technical-notebook/dotnet/http-protocol/technical-notebook-dotnet-http-protocol-post-method',
            'technical-notebook/dotnet/http-protocol/technical-notebook-dotnet-http-protocol-put-method',
            'technical-notebook/dotnet/http-protocol/technical-notebook-dotnet-http-protocol-delete-method',
          ],
        },
      ]
    },
    {
      type: 'category',
      label: 'OpenAI',
      items: [
        {
          type: 'category',
          label: 'DALL-E',
          items: [
            'technical-notebook/openai-gpt/dall-e/technical-notebook-consistent-image-reproduction-method',
            'technical-notebook/openai-gpt/dall-e/technical-notebook-my-site-image-generation-memo',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI問答メモ',
      items: [
        {
          type: 'category',
          label: 'C#関連',
          items: [
            'technical-notebook/ai-chat-memos/csharp/technical-notebook-ai-chat-memos-csharp-20240410-about-email-address',
            'technical-notebook/ai-chat-memos/csharp/technical-notebook-ai-chat-memos-csharp-20240412-about-exception-handling',
          ],
        },
      ],
    }
  ],
  profileSidebar: [
    'profiles/profiles-index',
    'profiles/profiles-self-introduction',
    'profiles/profiles-personal-development-environment',
  ],
};

export default sidebars;
