import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * サイドバーを作成することで、以下のことができます：
 - ドキュメントの順序付けられたグループを作成する
 - そのグループの各ドキュメントに対してサイドバーを表示する
 - 次へ/前へのナビゲーションを提供する

 サイドバーはファイルシステムから生成するか、ここで明示的に定義することができます。

 好きなだけサイドバーを作成できます。

 自動でサイドバーを作成できます。
  githubGuidelinesSidebar: [{type: 'autogenerated', dirName: 'github-guidelines'}],

 手動でサイドバーを作成することもできます。
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
 */
const sidebars: SidebarsConfig = {
  githubGuidelinesSidebar: [
    'github-guidelines/index',
    {
      type: 'category',
      label: 'GitHub Guidelines',
      /*link: {
        type: 'doc',
        id: 'github-guidelines/index', // ラベルクリック時のドキュメントを指定
      },*/
      items: [
        'github-guidelines/contents',  // ラベル内のドキュメントを指定
      ],
    },
  ],
  technicalPoliciesSidebar: [
    'technical-policies/index',
  ],
  technicalNotebookSidebar: [
    'technical-notebook/index',
  ],
  profileSidebar: [
    'profile/index',
  ],
};

export default sidebars;
