import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * サイドバーを作成することで、以下のことができます：
 - ドキュメントの順序付けられたグループを作成する
 - そのグループの各ドキュメントに対してサイドバーを表示する
 - 次へ/前へのナビゲーションを提供する

 サイドバーはファイルシステムから生成するか、ここで明示的に定義することができます。

 好きなだけサイドバーを作成できます。

 自動でサイドバーを作成できます。
  githubGuidelinesSidebar: [{type: 'autogenerated', dirName: 'github-guidelines'}],

 手動でサイドバーを作成することもできます。
  githubGuidelinesSidebar: [
    'github-guidelines/index',
    {
      type: 'category',
      label: 'GitHub Guidelines',
      link: {
        type: 'doc',
        id: 'github-guidelines/index',
      },
      items: [
        'github-guidelines/contents',
      ],
    },
  ],
 */
const sidebars: SidebarsConfig = {
  githubGuidelinesSidebar: [
    'github-guidelines/github-guidelines-index',
    `github-guidelines/github-guidelines-writing-guide`,
  ],
  technicalPoliciesSidebar: [
    'technical-policies/technical-policies-index',
    `technical-policies/technical-policies-writing-guide`,
  ],
  technicalNotebookSidebar: [
    'technical-notebook/technical-notebook-index',
    `technical-notebook/technical-notebook-writing-guide`,
  ],
  profileSidebar: [
    'profiles/profiles-index',
  ],
};

export default sidebars;
